[supervisord]
nodaemon=true

[program:flask]
command=python app.py
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:streamlit]
command=streamlit run skin_disease.py --server.port=$PORT --server.address=0.0.0.0 --server.headless true
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
